/** Generated by scripts/pack-pix.mjs — unique Grok Imagine cells per entity id. */
export const PIX_SHEETS = {
  "i0": {
    "src": "assets/pix/u-items-0.png",
    "cols": 8,
    "rows": 8
  },
  "i1": {
    "src": "assets/pix/u-items-1.png",
    "cols": 8,
    "rows": 8
  },
  "i2": {
    "src": "assets/pix/u-items-2.png",
    "cols": 8,
    "rows": 8
  },
  "i3": {
    "src": "assets/pix/u-items-3.png",
    "cols": 8,
    "rows": 8
  },
  "i4": {
    "src": "assets/pix/u-items-4.png",
    "cols": 8,
    "rows": 8
  },
  "i5": {
    "src": "assets/pix/u-items-5.png",
    "cols": 8,
    "rows": 8
  },
  "i6": {
    "src": "assets/pix/u-items-6.png",
    "cols": 8,
    "rows": 8
  },
  "i7": {
    "src": "assets/pix/u-items-7.png",
    "cols": 8,
    "rows": 8
  },
  "m0": {
    "src": "assets/pix/u-mon-0.png",
    "cols": 8,
    "rows": 8
  },
  "m1": {
    "src": "assets/pix/u-mon-1.png",
    "cols": 8,
    "rows": 8
  },
  "misc": {
    "src": "assets/pix/u-misc.png",
    "cols": 8,
    "rows": 8
  },
  "a0": {
    "src": "assets/pix/u-act-0.png",
    "cols": 8,
    "rows": 8
  },
  "a1": {
    "src": "assets/pix/u-act-1.png",
    "cols": 8,
    "rows": 8
  },
  "a2": {
    "src": "assets/pix/u-act-2.png",
    "cols": 8,
    "rows": 8
  },
  "a3": {
    "src": "assets/pix/u-act-3.png",
    "cols": 8,
    "rows": 8
  },
  "a4": {
    "src": "assets/pix/u-act-4.png",
    "cols": 8,
    "rows": 8
  },
  "a5": {
    "src": "assets/pix/u-act-5.png",
    "cols": 8,
    "rows": 8
  },
  "a6": {
    "src": "assets/pix/u-act-6.png",
    "cols": 8,
    "rows": 8
  },
  "skills": {
    "src": "assets/pix/atlas-skills.png",
    "cols": 5,
    "rows": 5
  }
};
export const PIX_EID = {
  "coins": [
    "i0",
    0,
    0
  ],
  "ashes": [
    "i0",
    1,
    0
  ],
  "bones": [
    "i0",
    2,
    0
  ],
  "essence": [
    "i0",
    3,
    0
  ],
  "hide": [
    "i0",
    4,
    0
  ],
  "feather": [
    "i0",
    5,
    0
  ],
  "thread": [
    "i0",
    6,
    0
  ],
  "seed-pouch": [
    "i0",
    7,
    0
  ],
  "bounty-token": [
    "i0",
    0,
    1
  ],
  "dungeon-key": [
    "i0",
    1,
    1
  ],
  "compost": [
    "i0",
    2,
    1
  ],
  "stardust": [
    "i0",
    3,
    1
  ],
  "fodder": [
    "i0",
    4,
    1
  ],
  "rune-gust": [
    "i0",
    5,
    1
  ],
  "rune-ember": [
    "i0",
    6,
    1
  ],
  "rune-tide": [
    "i0",
    7,
    1
  ],
  "rune-stone": [
    "i0",
    0,
    2
  ],
  "rune-mind": [
    "i0",
    1,
    2
  ],
  "rune-blood": [
    "i0",
    2,
    2
  ],
  "rune-void": [
    "i0",
    3,
    2
  ],
  "rune-star": [
    "i0",
    4,
    2
  ],
  "log-0": [
    "i0",
    5,
    2
  ],
  "ore-0": [
    "i0",
    6,
    2
  ],
  "bar-0": [
    "i0",
    7,
    2
  ],
  "fish-0": [
    "i0",
    0,
    3
  ],
  "food-0": [
    "i0",
    1,
    3
  ],
  "gem-0": [
    "i0",
    2,
    3
  ],
  "herb-0": [
    "i0",
    3,
    3
  ],
  "seed-0": [
    "i0",
    4,
    3
  ],
  "drift-saber": [
    "i0",
    5,
    3
  ],
  "drift-cleaver": [
    "i0",
    6,
    3
  ],
  "drift-needle": [
    "i0",
    7,
    3
  ],
  "drift-longbow": [
    "i0",
    0,
    4
  ],
  "drift-crozier": [
    "i0",
    1,
    4
  ],
  "drift-helm": [
    "i0",
    2,
    4
  ],
  "drift-body": [
    "i0",
    3,
    4
  ],
  "drift-legs": [
    "i0",
    4,
    4
  ],
  "drift-boots": [
    "i0",
    5,
    4
  ],
  "drift-gloves": [
    "i0",
    6,
    4
  ],
  "drift-shield": [
    "i0",
    7,
    4
  ],
  "drift-hide-cape": [
    "i0",
    0,
    5
  ],
  "drift-hide-body": [
    "i0",
    1,
    5
  ],
  "drift-hide-legs": [
    "i0",
    2,
    5
  ],
  "drift-hide-boots": [
    "i0",
    3,
    5
  ],
  "drift-hide-gloves": [
    "i0",
    4,
    5
  ],
  "drift-robe": [
    "i0",
    5,
    5
  ],
  "drift-amulet": [
    "i0",
    6,
    5
  ],
  "arrow-0": [
    "i0",
    7,
    5
  ],
  "potion-0": [
    "i0",
    0,
    6
  ],
  "log-1": [
    "i0",
    1,
    6
  ],
  "ore-1": [
    "i0",
    2,
    6
  ],
  "bar-1": [
    "i0",
    3,
    6
  ],
  "fish-1": [
    "i0",
    4,
    6
  ],
  "food-1": [
    "i0",
    5,
    6
  ],
  "gem-1": [
    "i0",
    6,
    6
  ],
  "herb-1": [
    "i0",
    7,
    6
  ],
  "seed-1": [
    "i0",
    0,
    7
  ],
  "copper-saber": [
    "i0",
    1,
    7
  ],
  "copper-cleaver": [
    "i0",
    2,
    7
  ],
  "copper-needle": [
    "i0",
    3,
    7
  ],
  "copper-longbow": [
    "i0",
    4,
    7
  ],
  "copper-crozier": [
    "i0",
    5,
    7
  ],
  "copper-helm": [
    "i0",
    6,
    7
  ],
  "copper-body": [
    "i0",
    7,
    7
  ],
  "copper-legs": [
    "i1",
    0,
    0
  ],
  "copper-boots": [
    "i1",
    1,
    0
  ],
  "copper-gloves": [
    "i1",
    2,
    0
  ],
  "copper-shield": [
    "i1",
    3,
    0
  ],
  "copper-hide-cape": [
    "i1",
    4,
    0
  ],
  "copper-hide-body": [
    "i1",
    5,
    0
  ],
  "copper-hide-legs": [
    "i1",
    6,
    0
  ],
  "copper-hide-boots": [
    "i1",
    7,
    0
  ],
  "copper-hide-gloves": [
    "i1",
    0,
    1
  ],
  "copper-robe": [
    "i1",
    1,
    1
  ],
  "copper-amulet": [
    "i1",
    2,
    1
  ],
  "arrow-1": [
    "i1",
    3,
    1
  ],
  "potion-1": [
    "i1",
    4,
    1
  ],
  "log-2": [
    "i1",
    5,
    1
  ],
  "ore-2": [
    "i1",
    6,
    1
  ],
  "bar-2": [
    "i1",
    7,
    1
  ],
  "fish-2": [
    "i1",
    0,
    2
  ],
  "food-2": [
    "i1",
    1,
    2
  ],
  "gem-2": [
    "i1",
    2,
    2
  ],
  "herb-2": [
    "i1",
    3,
    2
  ],
  "seed-2": [
    "i1",
    4,
    2
  ],
  "iron-saber": [
    "i1",
    5,
    2
  ],
  "iron-cleaver": [
    "i1",
    6,
    2
  ],
  "iron-needle": [
    "i1",
    7,
    2
  ],
  "iron-longbow": [
    "i1",
    0,
    3
  ],
  "iron-crozier": [
    "i1",
    1,
    3
  ],
  "iron-helm": [
    "i1",
    2,
    3
  ],
  "iron-body": [
    "i1",
    3,
    3
  ],
  "iron-legs": [
    "i1",
    4,
    3
  ],
  "iron-boots": [
    "i1",
    5,
    3
  ],
  "iron-gloves": [
    "i1",
    6,
    3
  ],
  "iron-shield": [
    "i1",
    7,
    3
  ],
  "iron-hide-cape": [
    "i1",
    0,
    4
  ],
  "iron-hide-body": [
    "i1",
    1,
    4
  ],
  "iron-hide-legs": [
    "i1",
    2,
    4
  ],
  "iron-hide-boots": [
    "i1",
    3,
    4
  ],
  "iron-hide-gloves": [
    "i1",
    4,
    4
  ],
  "iron-robe": [
    "i1",
    5,
    4
  ],
  "iron-amulet": [
    "i1",
    6,
    4
  ],
  "arrow-2": [
    "i1",
    7,
    4
  ],
  "potion-2": [
    "i1",
    0,
    5
  ],
  "log-3": [
    "i1",
    1,
    5
  ],
  "ore-3": [
    "i1",
    2,
    5
  ],
  "bar-3": [
    "i1",
    3,
    5
  ],
  "fish-3": [
    "i1",
    4,
    5
  ],
  "food-3": [
    "i1",
    5,
    5
  ],
  "gem-3": [
    "i1",
    6,
    5
  ],
  "herb-3": [
    "i1",
    7,
    5
  ],
  "seed-3": [
    "i1",
    0,
    6
  ],
  "steel-saber": [
    "i1",
    1,
    6
  ],
  "steel-cleaver": [
    "i1",
    2,
    6
  ],
  "steel-needle": [
    "i1",
    3,
    6
  ],
  "steel-longbow": [
    "i1",
    4,
    6
  ],
  "steel-crozier": [
    "i1",
    5,
    6
  ],
  "steel-helm": [
    "i1",
    6,
    6
  ],
  "steel-body": [
    "i1",
    7,
    6
  ],
  "steel-legs": [
    "i1",
    0,
    7
  ],
  "steel-boots": [
    "i1",
    1,
    7
  ],
  "steel-gloves": [
    "i1",
    2,
    7
  ],
  "steel-shield": [
    "i1",
    3,
    7
  ],
  "steel-hide-cape": [
    "i1",
    4,
    7
  ],
  "steel-hide-body": [
    "i1",
    5,
    7
  ],
  "steel-hide-legs": [
    "i1",
    6,
    7
  ],
  "steel-hide-boots": [
    "i1",
    7,
    7
  ],
  "steel-hide-gloves": [
    "i2",
    0,
    0
  ],
  "steel-robe": [
    "i2",
    1,
    0
  ],
  "steel-amulet": [
    "i2",
    2,
    0
  ],
  "arrow-3": [
    "i2",
    3,
    0
  ],
  "potion-3": [
    "i2",
    4,
    0
  ],
  "log-4": [
    "i2",
    5,
    0
  ],
  "ore-4": [
    "i2",
    6,
    0
  ],
  "bar-4": [
    "i2",
    7,
    0
  ],
  "fish-4": [
    "i2",
    0,
    1
  ],
  "food-4": [
    "i2",
    1,
    1
  ],
  "gem-4": [
    "i2",
    2,
    1
  ],
  "herb-4": [
    "i2",
    3,
    1
  ],
  "seed-4": [
    "i2",
    4,
    1
  ],
  "moonsteel-saber": [
    "i2",
    5,
    1
  ],
  "moonsteel-cleaver": [
    "i2",
    6,
    1
  ],
  "moonsteel-needle": [
    "i2",
    7,
    1
  ],
  "moonsteel-longbow": [
    "i2",
    0,
    2
  ],
  "moonsteel-crozier": [
    "i2",
    1,
    2
  ],
  "moonsteel-helm": [
    "i2",
    2,
    2
  ],
  "moonsteel-body": [
    "i2",
    3,
    2
  ],
  "moonsteel-legs": [
    "i2",
    4,
    2
  ],
  "moonsteel-boots": [
    "i2",
    5,
    2
  ],
  "moonsteel-gloves": [
    "i2",
    6,
    2
  ],
  "moonsteel-shield": [
    "i2",
    7,
    2
  ],
  "moonsteel-hide-cape": [
    "i2",
    0,
    3
  ],
  "moonsteel-hide-body": [
    "i2",
    1,
    3
  ],
  "moonsteel-hide-legs": [
    "i2",
    2,
    3
  ],
  "moonsteel-hide-boots": [
    "i2",
    3,
    3
  ],
  "moonsteel-hide-gloves": [
    "i2",
    4,
    3
  ],
  "moonsteel-robe": [
    "i2",
    5,
    3
  ],
  "moonsteel-amulet": [
    "i2",
    6,
    3
  ],
  "arrow-4": [
    "i2",
    7,
    3
  ],
  "potion-4": [
    "i2",
    0,
    4
  ],
  "log-5": [
    "i2",
    1,
    4
  ],
  "ore-5": [
    "i2",
    2,
    4
  ],
  "bar-5": [
    "i2",
    3,
    4
  ],
  "fish-5": [
    "i2",
    4,
    4
  ],
  "food-5": [
    "i2",
    5,
    4
  ],
  "gem-5": [
    "i2",
    6,
    4
  ],
  "herb-5": [
    "i2",
    7,
    4
  ],
  "seed-5": [
    "i2",
    0,
    5
  ],
  "adamant-saber": [
    "i2",
    1,
    5
  ],
  "adamant-cleaver": [
    "i2",
    2,
    5
  ],
  "adamant-needle": [
    "i2",
    3,
    5
  ],
  "adamant-longbow": [
    "i2",
    4,
    5
  ],
  "adamant-crozier": [
    "i2",
    5,
    5
  ],
  "adamant-helm": [
    "i2",
    6,
    5
  ],
  "adamant-body": [
    "i2",
    7,
    5
  ],
  "adamant-legs": [
    "i2",
    0,
    6
  ],
  "adamant-boots": [
    "i2",
    1,
    6
  ],
  "adamant-gloves": [
    "i2",
    2,
    6
  ],
  "adamant-shield": [
    "i2",
    3,
    6
  ],
  "adamant-hide-cape": [
    "i2",
    4,
    6
  ],
  "adamant-hide-body": [
    "i2",
    5,
    6
  ],
  "adamant-hide-legs": [
    "i2",
    6,
    6
  ],
  "adamant-hide-boots": [
    "i2",
    7,
    6
  ],
  "adamant-hide-gloves": [
    "i2",
    0,
    7
  ],
  "adamant-robe": [
    "i2",
    1,
    7
  ],
  "adamant-amulet": [
    "i2",
    2,
    7
  ],
  "arrow-5": [
    "i2",
    3,
    7
  ],
  "potion-5": [
    "i2",
    4,
    7
  ],
  "log-6": [
    "i2",
    5,
    7
  ],
  "ore-6": [
    "i2",
    6,
    7
  ],
  "bar-6": [
    "i2",
    7,
    7
  ],
  "fish-6": [
    "i3",
    0,
    0
  ],
  "food-6": [
    "i3",
    1,
    0
  ],
  "gem-6": [
    "i3",
    2,
    0
  ],
  "herb-6": [
    "i3",
    3,
    0
  ],
  "seed-6": [
    "i3",
    4,
    0
  ],
  "runebound-saber": [
    "i3",
    5,
    0
  ],
  "runebound-cleaver": [
    "i3",
    6,
    0
  ],
  "runebound-needle": [
    "i3",
    7,
    0
  ],
  "runebound-longbow": [
    "i3",
    0,
    1
  ],
  "runebound-crozier": [
    "i3",
    1,
    1
  ],
  "runebound-helm": [
    "i3",
    2,
    1
  ],
  "runebound-body": [
    "i3",
    3,
    1
  ],
  "runebound-legs": [
    "i3",
    4,
    1
  ],
  "runebound-boots": [
    "i3",
    5,
    1
  ],
  "runebound-gloves": [
    "i3",
    6,
    1
  ],
  "runebound-shield": [
    "i3",
    7,
    1
  ],
  "runebound-hide-cape": [
    "i3",
    0,
    2
  ],
  "runebound-hide-body": [
    "i3",
    1,
    2
  ],
  "runebound-hide-legs": [
    "i3",
    2,
    2
  ],
  "runebound-hide-boots": [
    "i3",
    3,
    2
  ],
  "runebound-hide-gloves": [
    "i3",
    4,
    2
  ],
  "runebound-robe": [
    "i3",
    5,
    2
  ],
  "runebound-amulet": [
    "i3",
    6,
    2
  ],
  "arrow-6": [
    "i3",
    7,
    2
  ],
  "potion-6": [
    "i3",
    0,
    3
  ],
  "log-7": [
    "i3",
    1,
    3
  ],
  "ore-7": [
    "i3",
    2,
    3
  ],
  "bar-7": [
    "i3",
    3,
    3
  ],
  "fish-7": [
    "i3",
    4,
    3
  ],
  "food-7": [
    "i3",
    5,
    3
  ],
  "gem-7": [
    "i3",
    6,
    3
  ],
  "herb-7": [
    "i3",
    7,
    3
  ],
  "seed-7": [
    "i3",
    0,
    4
  ],
  "wyrm-saber": [
    "i3",
    1,
    4
  ],
  "wyrm-cleaver": [
    "i3",
    2,
    4
  ],
  "wyrm-needle": [
    "i3",
    3,
    4
  ],
  "wyrm-longbow": [
    "i3",
    4,
    4
  ],
  "wyrm-crozier": [
    "i3",
    5,
    4
  ],
  "wyrm-helm": [
    "i3",
    6,
    4
  ],
  "wyrm-body": [
    "i3",
    7,
    4
  ],
  "wyrm-legs": [
    "i3",
    0,
    5
  ],
  "wyrm-boots": [
    "i3",
    1,
    5
  ],
  "wyrm-gloves": [
    "i3",
    2,
    5
  ],
  "wyrm-shield": [
    "i3",
    3,
    5
  ],
  "wyrm-hide-cape": [
    "i3",
    4,
    5
  ],
  "wyrm-hide-body": [
    "i3",
    5,
    5
  ],
  "wyrm-hide-legs": [
    "i3",
    6,
    5
  ],
  "wyrm-hide-boots": [
    "i3",
    7,
    5
  ],
  "wyrm-hide-gloves": [
    "i3",
    0,
    6
  ],
  "wyrm-robe": [
    "i3",
    1,
    6
  ],
  "wyrm-amulet": [
    "i3",
    2,
    6
  ],
  "arrow-7": [
    "i3",
    3,
    6
  ],
  "potion-7": [
    "i3",
    4,
    6
  ],
  "log-8": [
    "i3",
    5,
    6
  ],
  "ore-8": [
    "i3",
    6,
    6
  ],
  "bar-8": [
    "i3",
    7,
    6
  ],
  "fish-8": [
    "i3",
    0,
    7
  ],
  "food-8": [
    "i3",
    1,
    7
  ],
  "herb-8": [
    "i3",
    2,
    7
  ],
  "seed-8": [
    "i3",
    3,
    7
  ],
  "ancient-saber": [
    "i3",
    4,
    7
  ],
  "ancient-cleaver": [
    "i3",
    5,
    7
  ],
  "ancient-needle": [
    "i3",
    6,
    7
  ],
  "ancient-longbow": [
    "i3",
    7,
    7
  ],
  "ancient-crozier": [
    "i4",
    0,
    0
  ],
  "ancient-helm": [
    "i4",
    1,
    0
  ],
  "ancient-body": [
    "i4",
    2,
    0
  ],
  "ancient-legs": [
    "i4",
    3,
    0
  ],
  "ancient-boots": [
    "i4",
    4,
    0
  ],
  "ancient-gloves": [
    "i4",
    5,
    0
  ],
  "ancient-shield": [
    "i4",
    6,
    0
  ],
  "ancient-hide-cape": [
    "i4",
    7,
    0
  ],
  "ancient-hide-body": [
    "i4",
    0,
    1
  ],
  "ancient-hide-legs": [
    "i4",
    1,
    1
  ],
  "ancient-hide-boots": [
    "i4",
    2,
    1
  ],
  "ancient-hide-gloves": [
    "i4",
    3,
    1
  ],
  "ancient-robe": [
    "i4",
    4,
    1
  ],
  "ancient-amulet": [
    "i4",
    5,
    1
  ],
  "arrow-8": [
    "i4",
    6,
    1
  ],
  "potion-8": [
    "i4",
    7,
    1
  ],
  "log-9": [
    "i4",
    0,
    2
  ],
  "ore-9": [
    "i4",
    1,
    2
  ],
  "bar-9": [
    "i4",
    2,
    2
  ],
  "fish-9": [
    "i4",
    3,
    2
  ],
  "food-9": [
    "i4",
    4,
    2
  ],
  "herb-9": [
    "i4",
    5,
    2
  ],
  "seed-9": [
    "i4",
    6,
    2
  ],
  "celestial-saber": [
    "i4",
    7,
    2
  ],
  "celestial-cleaver": [
    "i4",
    0,
    3
  ],
  "celestial-needle": [
    "i4",
    1,
    3
  ],
  "celestial-longbow": [
    "i4",
    2,
    3
  ],
  "celestial-crozier": [
    "i4",
    3,
    3
  ],
  "celestial-helm": [
    "i4",
    4,
    3
  ],
  "celestial-body": [
    "i4",
    5,
    3
  ],
  "celestial-legs": [
    "i4",
    6,
    3
  ],
  "celestial-boots": [
    "i4",
    7,
    3
  ],
  "celestial-gloves": [
    "i4",
    0,
    4
  ],
  "celestial-shield": [
    "i4",
    1,
    4
  ],
  "celestial-hide-cape": [
    "i4",
    2,
    4
  ],
  "celestial-hide-body": [
    "i4",
    3,
    4
  ],
  "celestial-hide-legs": [
    "i4",
    4,
    4
  ],
  "celestial-hide-boots": [
    "i4",
    5,
    4
  ],
  "celestial-hide-gloves": [
    "i4",
    6,
    4
  ],
  "celestial-robe": [
    "i4",
    7,
    4
  ],
  "celestial-amulet": [
    "i4",
    0,
    5
  ],
  "arrow-9": [
    "i4",
    1,
    5
  ],
  "potion-9": [
    "i4",
    2,
    5
  ],
  "log-10": [
    "i4",
    3,
    5
  ],
  "ore-10": [
    "i4",
    4,
    5
  ],
  "bar-10": [
    "i4",
    5,
    5
  ],
  "fish-10": [
    "i4",
    6,
    5
  ],
  "food-10": [
    "i4",
    7,
    5
  ],
  "herb-10": [
    "i4",
    0,
    6
  ],
  "seed-10": [
    "i4",
    1,
    6
  ],
  "voidglass-saber": [
    "i4",
    2,
    6
  ],
  "voidglass-cleaver": [
    "i4",
    3,
    6
  ],
  "voidglass-needle": [
    "i4",
    4,
    6
  ],
  "voidglass-longbow": [
    "i4",
    5,
    6
  ],
  "voidglass-crozier": [
    "i4",
    6,
    6
  ],
  "voidglass-helm": [
    "i4",
    7,
    6
  ],
  "voidglass-body": [
    "i4",
    0,
    7
  ],
  "voidglass-legs": [
    "i4",
    1,
    7
  ],
  "voidglass-boots": [
    "i4",
    2,
    7
  ],
  "voidglass-gloves": [
    "i4",
    3,
    7
  ],
  "voidglass-shield": [
    "i4",
    4,
    7
  ],
  "voidglass-hide-cape": [
    "i4",
    5,
    7
  ],
  "voidglass-hide-body": [
    "i4",
    6,
    7
  ],
  "voidglass-hide-legs": [
    "i4",
    7,
    7
  ],
  "voidglass-hide-boots": [
    "i5",
    0,
    0
  ],
  "voidglass-hide-gloves": [
    "i5",
    1,
    0
  ],
  "voidglass-robe": [
    "i5",
    2,
    0
  ],
  "voidglass-amulet": [
    "i5",
    3,
    0
  ],
  "arrow-10": [
    "i5",
    4,
    0
  ],
  "potion-10": [
    "i5",
    5,
    0
  ],
  "log-11": [
    "i5",
    6,
    0
  ],
  "ore-11": [
    "i5",
    7,
    0
  ],
  "bar-11": [
    "i5",
    0,
    1
  ],
  "fish-11": [
    "i5",
    1,
    1
  ],
  "food-11": [
    "i5",
    2,
    1
  ],
  "herb-11": [
    "i5",
    3,
    1
  ],
  "seed-11": [
    "i5",
    4,
    1
  ],
  "mythic-saber": [
    "i5",
    5,
    1
  ],
  "mythic-cleaver": [
    "i5",
    6,
    1
  ],
  "mythic-needle": [
    "i5",
    7,
    1
  ],
  "mythic-longbow": [
    "i5",
    0,
    2
  ],
  "mythic-crozier": [
    "i5",
    1,
    2
  ],
  "mythic-helm": [
    "i5",
    2,
    2
  ],
  "mythic-body": [
    "i5",
    3,
    2
  ],
  "mythic-legs": [
    "i5",
    4,
    2
  ],
  "mythic-boots": [
    "i5",
    5,
    2
  ],
  "mythic-gloves": [
    "i5",
    6,
    2
  ],
  "mythic-shield": [
    "i5",
    7,
    2
  ],
  "mythic-hide-cape": [
    "i5",
    0,
    3
  ],
  "mythic-hide-body": [
    "i5",
    1,
    3
  ],
  "mythic-hide-legs": [
    "i5",
    2,
    3
  ],
  "mythic-hide-boots": [
    "i5",
    3,
    3
  ],
  "mythic-hide-gloves": [
    "i5",
    4,
    3
  ],
  "mythic-robe": [
    "i5",
    5,
    3
  ],
  "mythic-amulet": [
    "i5",
    6,
    3
  ],
  "arrow-11": [
    "i5",
    7,
    3
  ],
  "potion-11": [
    "i5",
    0,
    4
  ],
  "log-12": [
    "i5",
    1,
    4
  ],
  "ore-12": [
    "i5",
    2,
    4
  ],
  "bar-12": [
    "i5",
    3,
    4
  ],
  "fish-12": [
    "i5",
    4,
    4
  ],
  "food-12": [
    "i5",
    5,
    4
  ],
  "herb-12": [
    "i5",
    6,
    4
  ],
  "seed-12": [
    "i5",
    7,
    4
  ],
  "astral-saber": [
    "i5",
    0,
    5
  ],
  "astral-cleaver": [
    "i5",
    1,
    5
  ],
  "astral-needle": [
    "i5",
    2,
    5
  ],
  "astral-longbow": [
    "i5",
    3,
    5
  ],
  "astral-crozier": [
    "i5",
    4,
    5
  ],
  "astral-helm": [
    "i5",
    5,
    5
  ],
  "astral-body": [
    "i5",
    6,
    5
  ],
  "astral-legs": [
    "i5",
    7,
    5
  ],
  "astral-boots": [
    "i5",
    0,
    6
  ],
  "astral-gloves": [
    "i5",
    1,
    6
  ],
  "astral-shield": [
    "i5",
    2,
    6
  ],
  "astral-hide-cape": [
    "i5",
    3,
    6
  ],
  "astral-hide-body": [
    "i5",
    4,
    6
  ],
  "astral-hide-legs": [
    "i5",
    5,
    6
  ],
  "astral-hide-boots": [
    "i5",
    6,
    6
  ],
  "astral-hide-gloves": [
    "i5",
    7,
    6
  ],
  "astral-robe": [
    "i5",
    0,
    7
  ],
  "astral-amulet": [
    "i5",
    1,
    7
  ],
  "arrow-12": [
    "i5",
    2,
    7
  ],
  "potion-12": [
    "i5",
    3,
    7
  ],
  "log-13": [
    "i5",
    4,
    7
  ],
  "ore-13": [
    "i5",
    5,
    7
  ],
  "bar-13": [
    "i5",
    6,
    7
  ],
  "fish-13": [
    "i5",
    7,
    7
  ],
  "food-13": [
    "i6",
    0,
    0
  ],
  "herb-13": [
    "i6",
    1,
    0
  ],
  "seed-13": [
    "i6",
    2,
    0
  ],
  "veilborn-saber": [
    "i6",
    3,
    0
  ],
  "veilborn-cleaver": [
    "i6",
    4,
    0
  ],
  "veilborn-needle": [
    "i6",
    5,
    0
  ],
  "veilborn-longbow": [
    "i6",
    6,
    0
  ],
  "veilborn-crozier": [
    "i6",
    7,
    0
  ],
  "veilborn-helm": [
    "i6",
    0,
    1
  ],
  "veilborn-body": [
    "i6",
    1,
    1
  ],
  "veilborn-legs": [
    "i6",
    2,
    1
  ],
  "veilborn-boots": [
    "i6",
    3,
    1
  ],
  "veilborn-gloves": [
    "i6",
    4,
    1
  ],
  "veilborn-shield": [
    "i6",
    5,
    1
  ],
  "veilborn-hide-cape": [
    "i6",
    6,
    1
  ],
  "veilborn-hide-body": [
    "i6",
    7,
    1
  ],
  "veilborn-hide-legs": [
    "i6",
    0,
    2
  ],
  "veilborn-hide-boots": [
    "i6",
    1,
    2
  ],
  "veilborn-hide-gloves": [
    "i6",
    2,
    2
  ],
  "veilborn-robe": [
    "i6",
    3,
    2
  ],
  "veilborn-amulet": [
    "i6",
    4,
    2
  ],
  "arrow-13": [
    "i6",
    5,
    2
  ],
  "potion-13": [
    "i6",
    6,
    2
  ],
  "drift-hatchet": [
    "i6",
    7,
    2
  ],
  "copper-hatchet": [
    "i6",
    0,
    3
  ],
  "iron-hatchet": [
    "i6",
    1,
    3
  ],
  "steel-hatchet": [
    "i6",
    2,
    3
  ],
  "moonsteel-hatchet": [
    "i6",
    3,
    3
  ],
  "adamant-hatchet": [
    "i6",
    4,
    3
  ],
  "runebound-hatchet": [
    "i6",
    5,
    3
  ],
  "wyrm-hatchet": [
    "i6",
    6,
    3
  ],
  "ancient-hatchet": [
    "i6",
    7,
    3
  ],
  "celestial-hatchet": [
    "i6",
    0,
    4
  ],
  "voidglass-hatchet": [
    "i6",
    1,
    4
  ],
  "mythic-hatchet": [
    "i6",
    2,
    4
  ],
  "astral-hatchet": [
    "i6",
    3,
    4
  ],
  "veilborn-hatchet": [
    "i6",
    4,
    4
  ],
  "drift-pick": [
    "i6",
    5,
    4
  ],
  "copper-pick": [
    "i6",
    6,
    4
  ],
  "iron-pick": [
    "i6",
    7,
    4
  ],
  "steel-pick": [
    "i6",
    0,
    5
  ],
  "moonsteel-pick": [
    "i6",
    1,
    5
  ],
  "adamant-pick": [
    "i6",
    2,
    5
  ],
  "runebound-pick": [
    "i6",
    3,
    5
  ],
  "wyrm-pick": [
    "i6",
    4,
    5
  ],
  "ancient-pick": [
    "i6",
    5,
    5
  ],
  "celestial-pick": [
    "i6",
    6,
    5
  ],
  "voidglass-pick": [
    "i6",
    7,
    5
  ],
  "mythic-pick": [
    "i6",
    0,
    6
  ],
  "astral-pick": [
    "i6",
    1,
    6
  ],
  "veilborn-pick": [
    "i6",
    2,
    6
  ],
  "drift-rod": [
    "i6",
    3,
    6
  ],
  "copper-rod": [
    "i6",
    4,
    6
  ],
  "iron-rod": [
    "i6",
    5,
    6
  ],
  "steel-rod": [
    "i6",
    6,
    6
  ],
  "moonsteel-rod": [
    "i6",
    7,
    6
  ],
  "adamant-rod": [
    "i6",
    0,
    7
  ],
  "runebound-rod": [
    "i6",
    1,
    7
  ],
  "wyrm-rod": [
    "i6",
    2,
    7
  ],
  "ancient-rod": [
    "i6",
    3,
    7
  ],
  "celestial-rod": [
    "i6",
    4,
    7
  ],
  "voidglass-rod": [
    "i6",
    5,
    7
  ],
  "mythic-rod": [
    "i6",
    6,
    7
  ],
  "astral-rod": [
    "i6",
    7,
    7
  ],
  "veilborn-rod": [
    "i7",
    0,
    0
  ],
  "dock-warden": [
    "i7",
    1,
    0
  ],
  "lantern-cape": [
    "i7",
    2,
    0
  ],
  "veil-circlet": [
    "i7",
    3,
    0
  ],
  "star-signet": [
    "i7",
    4,
    0
  ],
  "cinder-docks-ash-mite": [
    "m0",
    0,
    0
  ],
  "cinder-docks-gutter-rat": [
    "m0",
    1,
    0
  ],
  "cinder-docks-dusk-imp": [
    "m0",
    2,
    0
  ],
  "cinder-docks-cinder-bat": [
    "m0",
    3,
    0
  ],
  "cinder-docks-moss-wolf": [
    "m0",
    4,
    0
  ],
  "cinder-docks-vault-crab": [
    "m0",
    5,
    0
  ],
  "lantern-sewers-sewer-lamp": [
    "m0",
    6,
    0
  ],
  "lantern-sewers-coin-leech": [
    "m0",
    7,
    0
  ],
  "lantern-sewers-grate-spider": [
    "m0",
    0,
    1
  ],
  "lantern-sewers-lantern-cultist": [
    "m0",
    1,
    1
  ],
  "lantern-sewers-filth-knight": [
    "m0",
    2,
    1
  ],
  "lantern-sewers-bell-wight": [
    "m0",
    3,
    1
  ],
  "ashfen-fen-tick": [
    "m0",
    4,
    1
  ],
  "ashfen-bog-knight": [
    "m0",
    5,
    1
  ],
  "ashfen-reed-hag": [
    "m0",
    6,
    1
  ],
  "ashfen-hollow-stag": [
    "m0",
    7,
    1
  ],
  "ashfen-silt-naga": [
    "m0",
    0,
    2
  ],
  "ashfen-ashfen-widow": [
    "m0",
    1,
    2
  ],
  "bastion-yard-yard-pikeman": [
    "m0",
    2,
    2
  ],
  "bastion-yard-bastion-boar": [
    "m0",
    3,
    2
  ],
  "bastion-yard-drill-sarge": [
    "m0",
    4,
    2
  ],
  "bastion-yard-forge-wasp": [
    "m0",
    5,
    2
  ],
  "bastion-yard-banner-ghoul": [
    "m0",
    6,
    2
  ],
  "bastion-yard-keep-mastiff": [
    "m0",
    7,
    2
  ],
  "choir-vaults-psalm-moth": [
    "m0",
    0,
    3
  ],
  "choir-vaults-choir-ghoul": [
    "m0",
    1,
    3
  ],
  "choir-vaults-relic-thief": [
    "m0",
    2,
    3
  ],
  "choir-vaults-mirror-owl": [
    "m0",
    3,
    3
  ],
  "choir-vaults-censer-imp": [
    "m0",
    4,
    3
  ],
  "choir-vaults-vault-cantor": [
    "m0",
    5,
    3
  ],
  "saltglass-coast-glass-gull": [
    "m0",
    6,
    3
  ],
  "saltglass-coast-salt-hydra": [
    "m0",
    7,
    3
  ],
  "saltglass-coast-tide-monk": [
    "m0",
    0,
    4
  ],
  "saltglass-coast-coral-wolf": [
    "m0",
    1,
    4
  ],
  "saltglass-coast-drift-siren": [
    "m0",
    2,
    4
  ],
  "saltglass-coast-coast-leviathan": [
    "m0",
    3,
    4
  ],
  "pyre-warrens-cinder-ant": [
    "m0",
    4,
    4
  ],
  "pyre-warrens-pyre-troll": [
    "m0",
    5,
    4
  ],
  "pyre-warrens-coal-wight": [
    "m0",
    6,
    4
  ],
  "pyre-warrens-smoke-drake": [
    "m0",
    7,
    4
  ],
  "pyre-warrens-kiln-knight": [
    "m0",
    0,
    5
  ],
  "pyre-warrens-furnace-heart": [
    "m0",
    1,
    5
  ],
  "oathbreak-march-broken-squire": [
    "m0",
    2,
    5
  ],
  "oathbreak-march-oathbreaker": [
    "m0",
    3,
    5
  ],
  "oathbreak-march-march-hound": [
    "m0",
    4,
    5
  ],
  "oathbreak-march-rust-paladin": [
    "m0",
    5,
    5
  ],
  "oathbreak-march-standard-wraith": [
    "m0",
    6,
    5
  ],
  "oathbreak-march-vow-eater": [
    "m0",
    7,
    5
  ],
  "starfall-cut-meteor-rat": [
    "m0",
    0,
    6
  ],
  "starfall-cut-star-hyena": [
    "m0",
    1,
    6
  ],
  "starfall-cut-cut-jackal": [
    "m0",
    2,
    6
  ],
  "starfall-cut-comet-archer": [
    "m0",
    3,
    6
  ],
  "starfall-cut-falling-nun": [
    "m0",
    4,
    6
  ],
  "starfall-cut-glass-drake": [
    "m0",
    5,
    6
  ],
  "void-orchard-orchard-mite": [
    "m0",
    6,
    6
  ],
  "void-orchard-void-moth": [
    "m0",
    7,
    6
  ],
  "void-orchard-ripe-spectre": [
    "m0",
    0,
    7
  ],
  "void-orchard-black-bloom": [
    "m0",
    1,
    7
  ],
  "void-orchard-root-seraph": [
    "m0",
    2,
    7
  ],
  "void-orchard-orchard-titan": [
    "m0",
    3,
    7
  ],
  "seraph-stair-step-wisp": [
    "m0",
    4,
    7
  ],
  "seraph-stair-stair-gargoyle": [
    "m0",
    5,
    7
  ],
  "seraph-stair-veil-seraph": [
    "m0",
    6,
    7
  ],
  "seraph-stair-choir-giant": [
    "m0",
    7,
    7
  ],
  "seraph-stair-halo-wight": [
    "m1",
    0,
    0
  ],
  "seraph-stair-spire-judge": [
    "m1",
    1,
    0
  ],
  "thornheart-thorn-tick": [
    "m1",
    2,
    0
  ],
  "thornheart-heart-bramble": [
    "m1",
    3,
    0
  ],
  "thornheart-thorn-colossus": [
    "m1",
    4,
    0
  ],
  "thornheart-rose-wraith": [
    "m1",
    5,
    0
  ],
  "thornheart-crown-hydra": [
    "m1",
    6,
    0
  ],
  "thornheart-veil-tyrant": [
    "m1",
    7,
    0
  ],
  "drowned-harbor-dredge-crab": [
    "m1",
    0,
    1
  ],
  "drowned-harbor-moon-eel": [
    "m1",
    1,
    1
  ],
  "drowned-harbor-harbor-priest": [
    "m1",
    2,
    1
  ],
  "drowned-harbor-chain-diver": [
    "m1",
    3,
    1
  ],
  "drowned-harbor-fog-captain": [
    "m1",
    4,
    1
  ],
  "drowned-harbor-abyss-bell": [
    "m1",
    5,
    1
  ],
  "slag-hollow-quarry-tick": [
    "m1",
    6,
    1
  ],
  "slag-hollow-slag-golem": [
    "m1",
    7,
    1
  ],
  "slag-hollow-pick-wraith": [
    "m1",
    0,
    2
  ],
  "slag-hollow-ore-hydra": [
    "m1",
    1,
    2
  ],
  "slag-hollow-deep-autarch": [
    "m1",
    2,
    2
  ],
  "slag-hollow-vein-sovereign": [
    "m1",
    3,
    2
  ],
  "silent-archive-archive-moth": [
    "m1",
    4,
    2
  ],
  "silent-archive-ink-wight": [
    "m1",
    5,
    2
  ],
  "silent-archive-index-demon": [
    "m1",
    6,
    2
  ],
  "silent-archive-vellum-drake": [
    "m1",
    7,
    2
  ],
  "silent-archive-silent-curator": [
    "m1",
    0,
    3
  ],
  "silent-archive-codex-beast": [
    "m1",
    1,
    3
  ],
  "drove-graves-ranch-tick": [
    "m1",
    2,
    3
  ],
  "drove-graves-drove-shade": [
    "m1",
    3,
    3
  ],
  "drove-graves-sire-ghost": [
    "m1",
    4,
    3
  ],
  "drove-graves-wool-wraith": [
    "m1",
    5,
    3
  ],
  "drove-graves-pen-horror": [
    "m1",
    6,
    3
  ],
  "drove-graves-herd-king": [
    "m1",
    7,
    3
  ],
  "rotfield-plot-beetle": [
    "m1",
    0,
    4
  ],
  "rotfield-compost-wight": [
    "m1",
    1,
    4
  ],
  "rotfield-seed-hag": [
    "m1",
    2,
    4
  ],
  "rotfield-vine-serpent": [
    "m1",
    3,
    4
  ],
  "rotfield-harvest-golem": [
    "m1",
    4,
    4
  ],
  "rotfield-grove-reaper": [
    "m1",
    5,
    4
  ],
  "orbit-cloister-chart-imp": [
    "m1",
    6,
    4
  ],
  "orbit-cloister-astrolabe-eye": [
    "m1",
    7,
    4
  ],
  "orbit-cloister-orbit-wraith": [
    "m1",
    0,
    5
  ],
  "orbit-cloister-nova-hound": [
    "m1",
    1,
    5
  ],
  "orbit-cloister-eclipse-monk": [
    "m1",
    2,
    5
  ],
  "orbit-cloister-star-regent": [
    "m1",
    3,
    5
  ],
  "guild-crucible-guild-duelist": [
    "m1",
    4,
    5
  ],
  "guild-crucible-taskmaster": [
    "m1",
    5,
    5
  ],
  "guild-crucible-rank-serpent": [
    "m1",
    6,
    5
  ],
  "guild-crucible-seal-knight": [
    "m1",
    7,
    5
  ],
  "guild-crucible-master-shade": [
    "m1",
    0,
    6
  ],
  "guild-crucible-guild-tyrant": [
    "m1",
    1,
    6
  ],
  "the-last-page-last-candle": [
    "m1",
    2,
    6
  ],
  "the-last-page-dusk-judge": [
    "m1",
    3,
    6
  ],
  "the-last-page-veilborn-lion": [
    "m1",
    4,
    6
  ],
  "the-last-page-citadel-echo": [
    "m1",
    5,
    6
  ],
  "the-last-page-workshop-god": [
    "m1",
    6,
    6
  ],
  "the-last-page-the-ledger": [
    "m1",
    7,
    6
  ],
  "dock-vault-boss": [
    "m1",
    0,
    7
  ],
  "sewer-reliquary-boss": [
    "m1",
    1,
    7
  ],
  "fen-crown-boss": [
    "m1",
    2,
    7
  ],
  "choir-spire-boss": [
    "m1",
    3,
    7
  ],
  "pyre-cathedral-boss": [
    "m1",
    4,
    7
  ],
  "oathkeep-boss": [
    "m1",
    5,
    7
  ],
  "starwell-boss": [
    "m1",
    6,
    7
  ],
  "veilheart-boss": [
    "m1",
    7,
    7
  ],
  "timber-0": [
    "a0",
    0,
    0
  ],
  "vein-0": [
    "a0",
    1,
    0
  ],
  "smelt-0": [
    "a0",
    2,
    0
  ],
  "trawl-0": [
    "a0",
    3,
    0
  ],
  "cook-0": [
    "a0",
    4,
    0
  ],
  "ember-0": [
    "a0",
    5,
    0
  ],
  "smith-drift-saber": [
    "a0",
    6,
    0
  ],
  "smith-drift-cleaver": [
    "a0",
    7,
    0
  ],
  "smith-drift-needle": [
    "a0",
    0,
    1
  ],
  "smith-drift-crozier": [
    "a0",
    1,
    1
  ],
  "smith-drift-helm": [
    "a0",
    2,
    1
  ],
  "smith-drift-body": [
    "a0",
    3,
    1
  ],
  "smith-drift-legs": [
    "a0",
    4,
    1
  ],
  "smith-drift-boots": [
    "a0",
    5,
    1
  ],
  "smith-drift-gloves": [
    "a0",
    6,
    1
  ],
  "smith-drift-shield": [
    "a0",
    7,
    1
  ],
  "loom-drift-hide-cape": [
    "a0",
    0,
    2
  ],
  "loom-drift-hide-body": [
    "a0",
    1,
    2
  ],
  "loom-drift-hide-legs": [
    "a0",
    2,
    2
  ],
  "loom-drift-hide-boots": [
    "a0",
    3,
    2
  ],
  "loom-drift-hide-gloves": [
    "a0",
    4,
    2
  ],
  "loom-drift-robe": [
    "a0",
    5,
    2
  ],
  "loom-drift-amulet": [
    "a0",
    6,
    2
  ],
  "fletch-arrow-0": [
    "a0",
    7,
    2
  ],
  "fletch-bow-0": [
    "a0",
    0,
    3
  ],
  "vial-0": [
    "a0",
    1,
    3
  ],
  "sigil-0": [
    "a0",
    2,
    3
  ],
  "timber-1": [
    "a0",
    3,
    3
  ],
  "vein-1": [
    "a0",
    4,
    3
  ],
  "smelt-1": [
    "a0",
    5,
    3
  ],
  "trawl-1": [
    "a0",
    6,
    3
  ],
  "cook-1": [
    "a0",
    7,
    3
  ],
  "ember-1": [
    "a0",
    0,
    4
  ],
  "smith-copper-saber": [
    "a0",
    1,
    4
  ],
  "smith-copper-cleaver": [
    "a0",
    2,
    4
  ],
  "smith-copper-needle": [
    "a0",
    3,
    4
  ],
  "smith-copper-crozier": [
    "a0",
    4,
    4
  ],
  "smith-copper-helm": [
    "a0",
    5,
    4
  ],
  "smith-copper-body": [
    "a0",
    6,
    4
  ],
  "smith-copper-legs": [
    "a0",
    7,
    4
  ],
  "smith-copper-boots": [
    "a0",
    0,
    5
  ],
  "smith-copper-gloves": [
    "a0",
    1,
    5
  ],
  "smith-copper-shield": [
    "a0",
    2,
    5
  ],
  "loom-copper-hide-cape": [
    "a0",
    3,
    5
  ],
  "loom-copper-hide-body": [
    "a0",
    4,
    5
  ],
  "loom-copper-hide-legs": [
    "a0",
    5,
    5
  ],
  "loom-copper-hide-boots": [
    "a0",
    6,
    5
  ],
  "loom-copper-hide-gloves": [
    "a0",
    7,
    5
  ],
  "loom-copper-robe": [
    "a0",
    0,
    6
  ],
  "loom-copper-amulet": [
    "a0",
    1,
    6
  ],
  "fletch-arrow-1": [
    "a0",
    2,
    6
  ],
  "fletch-bow-1": [
    "a0",
    3,
    6
  ],
  "vial-1": [
    "a0",
    4,
    6
  ],
  "sigil-1": [
    "a0",
    5,
    6
  ],
  "timber-2": [
    "a0",
    6,
    6
  ],
  "vein-2": [
    "a0",
    7,
    6
  ],
  "smelt-2": [
    "a0",
    0,
    7
  ],
  "trawl-2": [
    "a0",
    1,
    7
  ],
  "cook-2": [
    "a0",
    2,
    7
  ],
  "ember-2": [
    "a0",
    3,
    7
  ],
  "smith-iron-saber": [
    "a0",
    4,
    7
  ],
  "smith-iron-cleaver": [
    "a0",
    5,
    7
  ],
  "smith-iron-needle": [
    "a0",
    6,
    7
  ],
  "smith-iron-crozier": [
    "a0",
    7,
    7
  ],
  "smith-iron-helm": [
    "a1",
    0,
    0
  ],
  "smith-iron-body": [
    "a1",
    1,
    0
  ],
  "smith-iron-legs": [
    "a1",
    2,
    0
  ],
  "smith-iron-boots": [
    "a1",
    3,
    0
  ],
  "smith-iron-gloves": [
    "a1",
    4,
    0
  ],
  "smith-iron-shield": [
    "a1",
    5,
    0
  ],
  "loom-iron-hide-cape": [
    "a1",
    6,
    0
  ],
  "loom-iron-hide-body": [
    "a1",
    7,
    0
  ],
  "loom-iron-hide-legs": [
    "a1",
    0,
    1
  ],
  "loom-iron-hide-boots": [
    "a1",
    1,
    1
  ],
  "loom-iron-hide-gloves": [
    "a1",
    2,
    1
  ],
  "loom-iron-robe": [
    "a1",
    3,
    1
  ],
  "loom-iron-amulet": [
    "a1",
    4,
    1
  ],
  "fletch-arrow-2": [
    "a1",
    5,
    1
  ],
  "fletch-bow-2": [
    "a1",
    6,
    1
  ],
  "vial-2": [
    "a1",
    7,
    1
  ],
  "sigil-2": [
    "a1",
    0,
    2
  ],
  "timber-3": [
    "a1",
    1,
    2
  ],
  "vein-3": [
    "a1",
    2,
    2
  ],
  "smelt-3": [
    "a1",
    3,
    2
  ],
  "trawl-3": [
    "a1",
    4,
    2
  ],
  "cook-3": [
    "a1",
    5,
    2
  ],
  "ember-3": [
    "a1",
    6,
    2
  ],
  "smith-steel-saber": [
    "a1",
    7,
    2
  ],
  "smith-steel-cleaver": [
    "a1",
    0,
    3
  ],
  "smith-steel-needle": [
    "a1",
    1,
    3
  ],
  "smith-steel-crozier": [
    "a1",
    2,
    3
  ],
  "smith-steel-helm": [
    "a1",
    3,
    3
  ],
  "smith-steel-body": [
    "a1",
    4,
    3
  ],
  "smith-steel-legs": [
    "a1",
    5,
    3
  ],
  "smith-steel-boots": [
    "a1",
    6,
    3
  ],
  "smith-steel-gloves": [
    "a1",
    7,
    3
  ],
  "smith-steel-shield": [
    "a1",
    0,
    4
  ],
  "loom-steel-hide-cape": [
    "a1",
    1,
    4
  ],
  "loom-steel-hide-body": [
    "a1",
    2,
    4
  ],
  "loom-steel-hide-legs": [
    "a1",
    3,
    4
  ],
  "loom-steel-hide-boots": [
    "a1",
    4,
    4
  ],
  "loom-steel-hide-gloves": [
    "a1",
    5,
    4
  ],
  "loom-steel-robe": [
    "a1",
    6,
    4
  ],
  "loom-steel-amulet": [
    "a1",
    7,
    4
  ],
  "fletch-arrow-3": [
    "a1",
    0,
    5
  ],
  "fletch-bow-3": [
    "a1",
    1,
    5
  ],
  "vial-3": [
    "a1",
    2,
    5
  ],
  "sigil-3": [
    "a1",
    3,
    5
  ],
  "timber-4": [
    "a1",
    4,
    5
  ],
  "vein-4": [
    "a1",
    5,
    5
  ],
  "smelt-4": [
    "a1",
    6,
    5
  ],
  "trawl-4": [
    "a1",
    7,
    5
  ],
  "cook-4": [
    "a1",
    0,
    6
  ],
  "ember-4": [
    "a1",
    1,
    6
  ],
  "smith-moonsteel-saber": [
    "a1",
    2,
    6
  ],
  "smith-moonsteel-cleaver": [
    "a1",
    3,
    6
  ],
  "smith-moonsteel-needle": [
    "a1",
    4,
    6
  ],
  "smith-moonsteel-crozier": [
    "a1",
    5,
    6
  ],
  "smith-moonsteel-helm": [
    "a1",
    6,
    6
  ],
  "smith-moonsteel-body": [
    "a1",
    7,
    6
  ],
  "smith-moonsteel-legs": [
    "a1",
    0,
    7
  ],
  "smith-moonsteel-boots": [
    "a1",
    1,
    7
  ],
  "smith-moonsteel-gloves": [
    "a1",
    2,
    7
  ],
  "smith-moonsteel-shield": [
    "a1",
    3,
    7
  ],
  "loom-moonsteel-hide-cape": [
    "a1",
    4,
    7
  ],
  "loom-moonsteel-hide-body": [
    "a1",
    5,
    7
  ],
  "loom-moonsteel-hide-legs": [
    "a1",
    6,
    7
  ],
  "loom-moonsteel-hide-boots": [
    "a1",
    7,
    7
  ],
  "loom-moonsteel-hide-gloves": [
    "a2",
    0,
    0
  ],
  "loom-moonsteel-robe": [
    "a2",
    1,
    0
  ],
  "loom-moonsteel-amulet": [
    "a2",
    2,
    0
  ],
  "fletch-arrow-4": [
    "a2",
    3,
    0
  ],
  "fletch-bow-4": [
    "a2",
    4,
    0
  ],
  "vial-4": [
    "a2",
    5,
    0
  ],
  "sigil-4": [
    "a2",
    6,
    0
  ],
  "timber-5": [
    "a2",
    7,
    0
  ],
  "vein-5": [
    "a2",
    0,
    1
  ],
  "smelt-5": [
    "a2",
    1,
    1
  ],
  "trawl-5": [
    "a2",
    2,
    1
  ],
  "cook-5": [
    "a2",
    3,
    1
  ],
  "ember-5": [
    "a2",
    4,
    1
  ],
  "smith-adamant-saber": [
    "a2",
    5,
    1
  ],
  "smith-adamant-cleaver": [
    "a2",
    6,
    1
  ],
  "smith-adamant-needle": [
    "a2",
    7,
    1
  ],
  "smith-adamant-crozier": [
    "a2",
    0,
    2
  ],
  "smith-adamant-helm": [
    "a2",
    1,
    2
  ],
  "smith-adamant-body": [
    "a2",
    2,
    2
  ],
  "smith-adamant-legs": [
    "a2",
    3,
    2
  ],
  "smith-adamant-boots": [
    "a2",
    4,
    2
  ],
  "smith-adamant-gloves": [
    "a2",
    5,
    2
  ],
  "smith-adamant-shield": [
    "a2",
    6,
    2
  ],
  "loom-adamant-hide-cape": [
    "a2",
    7,
    2
  ],
  "loom-adamant-hide-body": [
    "a2",
    0,
    3
  ],
  "loom-adamant-hide-legs": [
    "a2",
    1,
    3
  ],
  "loom-adamant-hide-boots": [
    "a2",
    2,
    3
  ],
  "loom-adamant-hide-gloves": [
    "a2",
    3,
    3
  ],
  "loom-adamant-robe": [
    "a2",
    4,
    3
  ],
  "loom-adamant-amulet": [
    "a2",
    5,
    3
  ],
  "fletch-arrow-5": [
    "a2",
    6,
    3
  ],
  "fletch-bow-5": [
    "a2",
    7,
    3
  ],
  "vial-5": [
    "a2",
    0,
    4
  ],
  "sigil-5": [
    "a2",
    1,
    4
  ],
  "timber-6": [
    "a2",
    2,
    4
  ],
  "vein-6": [
    "a2",
    3,
    4
  ],
  "smelt-6": [
    "a2",
    4,
    4
  ],
  "trawl-6": [
    "a2",
    5,
    4
  ],
  "cook-6": [
    "a2",
    6,
    4
  ],
  "ember-6": [
    "a2",
    7,
    4
  ],
  "smith-runebound-saber": [
    "a2",
    0,
    5
  ],
  "smith-runebound-cleaver": [
    "a2",
    1,
    5
  ],
  "smith-runebound-needle": [
    "a2",
    2,
    5
  ],
  "smith-runebound-crozier": [
    "a2",
    3,
    5
  ],
  "smith-runebound-helm": [
    "a2",
    4,
    5
  ],
  "smith-runebound-body": [
    "a2",
    5,
    5
  ],
  "smith-runebound-legs": [
    "a2",
    6,
    5
  ],
  "smith-runebound-boots": [
    "a2",
    7,
    5
  ],
  "smith-runebound-gloves": [
    "a2",
    0,
    6
  ],
  "smith-runebound-shield": [
    "a2",
    1,
    6
  ],
  "loom-runebound-hide-cape": [
    "a2",
    2,
    6
  ],
  "loom-runebound-hide-body": [
    "a2",
    3,
    6
  ],
  "loom-runebound-hide-legs": [
    "a2",
    4,
    6
  ],
  "loom-runebound-hide-boots": [
    "a2",
    5,
    6
  ],
  "loom-runebound-hide-gloves": [
    "a2",
    6,
    6
  ],
  "loom-runebound-robe": [
    "a2",
    7,
    6
  ],
  "loom-runebound-amulet": [
    "a2",
    0,
    7
  ],
  "fletch-arrow-6": [
    "a2",
    1,
    7
  ],
  "fletch-bow-6": [
    "a2",
    2,
    7
  ],
  "vial-6": [
    "a2",
    3,
    7
  ],
  "sigil-6": [
    "a2",
    4,
    7
  ],
  "timber-7": [
    "a2",
    5,
    7
  ],
  "vein-7": [
    "a2",
    6,
    7
  ],
  "smelt-7": [
    "a2",
    7,
    7
  ],
  "trawl-7": [
    "a3",
    0,
    0
  ],
  "cook-7": [
    "a3",
    1,
    0
  ],
  "ember-7": [
    "a3",
    2,
    0
  ],
  "smith-wyrm-saber": [
    "a3",
    3,
    0
  ],
  "smith-wyrm-cleaver": [
    "a3",
    4,
    0
  ],
  "smith-wyrm-needle": [
    "a3",
    5,
    0
  ],
  "smith-wyrm-crozier": [
    "a3",
    6,
    0
  ],
  "smith-wyrm-helm": [
    "a3",
    7,
    0
  ],
  "smith-wyrm-body": [
    "a3",
    0,
    1
  ],
  "smith-wyrm-legs": [
    "a3",
    1,
    1
  ],
  "smith-wyrm-boots": [
    "a3",
    2,
    1
  ],
  "smith-wyrm-gloves": [
    "a3",
    3,
    1
  ],
  "smith-wyrm-shield": [
    "a3",
    4,
    1
  ],
  "loom-wyrm-hide-cape": [
    "a3",
    5,
    1
  ],
  "loom-wyrm-hide-body": [
    "a3",
    6,
    1
  ],
  "loom-wyrm-hide-legs": [
    "a3",
    7,
    1
  ],
  "loom-wyrm-hide-boots": [
    "a3",
    0,
    2
  ],
  "loom-wyrm-hide-gloves": [
    "a3",
    1,
    2
  ],
  "loom-wyrm-robe": [
    "a3",
    2,
    2
  ],
  "loom-wyrm-amulet": [
    "a3",
    3,
    2
  ],
  "fletch-arrow-7": [
    "a3",
    4,
    2
  ],
  "fletch-bow-7": [
    "a3",
    5,
    2
  ],
  "vial-7": [
    "a3",
    6,
    2
  ],
  "sigil-7": [
    "a3",
    7,
    2
  ],
  "timber-8": [
    "a3",
    0,
    3
  ],
  "vein-8": [
    "a3",
    1,
    3
  ],
  "smelt-8": [
    "a3",
    2,
    3
  ],
  "trawl-8": [
    "a3",
    3,
    3
  ],
  "cook-8": [
    "a3",
    4,
    3
  ],
  "ember-8": [
    "a3",
    5,
    3
  ],
  "smith-ancient-saber": [
    "a3",
    6,
    3
  ],
  "smith-ancient-cleaver": [
    "a3",
    7,
    3
  ],
  "smith-ancient-needle": [
    "a3",
    0,
    4
  ],
  "smith-ancient-crozier": [
    "a3",
    1,
    4
  ],
  "smith-ancient-helm": [
    "a3",
    2,
    4
  ],
  "smith-ancient-body": [
    "a3",
    3,
    4
  ],
  "smith-ancient-legs": [
    "a3",
    4,
    4
  ],
  "smith-ancient-boots": [
    "a3",
    5,
    4
  ],
  "smith-ancient-gloves": [
    "a3",
    6,
    4
  ],
  "smith-ancient-shield": [
    "a3",
    7,
    4
  ],
  "loom-ancient-hide-cape": [
    "a3",
    0,
    5
  ],
  "loom-ancient-hide-body": [
    "a3",
    1,
    5
  ],
  "loom-ancient-hide-legs": [
    "a3",
    2,
    5
  ],
  "loom-ancient-hide-boots": [
    "a3",
    3,
    5
  ],
  "loom-ancient-hide-gloves": [
    "a3",
    4,
    5
  ],
  "loom-ancient-robe": [
    "a3",
    5,
    5
  ],
  "loom-ancient-amulet": [
    "a3",
    6,
    5
  ],
  "fletch-arrow-8": [
    "a3",
    7,
    5
  ],
  "fletch-bow-8": [
    "a3",
    0,
    6
  ],
  "vial-8": [
    "a3",
    1,
    6
  ],
  "sigil-8": [
    "a3",
    2,
    6
  ],
  "timber-9": [
    "a3",
    3,
    6
  ],
  "vein-9": [
    "a3",
    4,
    6
  ],
  "smelt-9": [
    "a3",
    5,
    6
  ],
  "trawl-9": [
    "a3",
    6,
    6
  ],
  "cook-9": [
    "a3",
    7,
    6
  ],
  "ember-9": [
    "a3",
    0,
    7
  ],
  "smith-celestial-saber": [
    "a3",
    1,
    7
  ],
  "smith-celestial-cleaver": [
    "a3",
    2,
    7
  ],
  "smith-celestial-needle": [
    "a3",
    3,
    7
  ],
  "smith-celestial-crozier": [
    "a3",
    4,
    7
  ],
  "smith-celestial-helm": [
    "a3",
    5,
    7
  ],
  "smith-celestial-body": [
    "a3",
    6,
    7
  ],
  "smith-celestial-legs": [
    "a3",
    7,
    7
  ],
  "smith-celestial-boots": [
    "a4",
    0,
    0
  ],
  "smith-celestial-gloves": [
    "a4",
    1,
    0
  ],
  "smith-celestial-shield": [
    "a4",
    2,
    0
  ],
  "loom-celestial-hide-cape": [
    "a4",
    3,
    0
  ],
  "loom-celestial-hide-body": [
    "a4",
    4,
    0
  ],
  "loom-celestial-hide-legs": [
    "a4",
    5,
    0
  ],
  "loom-celestial-hide-boots": [
    "a4",
    6,
    0
  ],
  "loom-celestial-hide-gloves": [
    "a4",
    7,
    0
  ],
  "loom-celestial-robe": [
    "a4",
    0,
    1
  ],
  "loom-celestial-amulet": [
    "a4",
    1,
    1
  ],
  "fletch-arrow-9": [
    "a4",
    2,
    1
  ],
  "fletch-bow-9": [
    "a4",
    3,
    1
  ],
  "vial-9": [
    "a4",
    4,
    1
  ],
  "sigil-9": [
    "a4",
    5,
    1
  ],
  "timber-10": [
    "a4",
    6,
    1
  ],
  "vein-10": [
    "a4",
    7,
    1
  ],
  "smelt-10": [
    "a4",
    0,
    2
  ],
  "trawl-10": [
    "a4",
    1,
    2
  ],
  "cook-10": [
    "a4",
    2,
    2
  ],
  "ember-10": [
    "a4",
    3,
    2
  ],
  "smith-voidglass-saber": [
    "a4",
    4,
    2
  ],
  "smith-voidglass-cleaver": [
    "a4",
    5,
    2
  ],
  "smith-voidglass-needle": [
    "a4",
    6,
    2
  ],
  "smith-voidglass-crozier": [
    "a4",
    7,
    2
  ],
  "smith-voidglass-helm": [
    "a4",
    0,
    3
  ],
  "smith-voidglass-body": [
    "a4",
    1,
    3
  ],
  "smith-voidglass-legs": [
    "a4",
    2,
    3
  ],
  "smith-voidglass-boots": [
    "a4",
    3,
    3
  ],
  "smith-voidglass-gloves": [
    "a4",
    4,
    3
  ],
  "smith-voidglass-shield": [
    "a4",
    5,
    3
  ],
  "loom-voidglass-hide-cape": [
    "a4",
    6,
    3
  ],
  "loom-voidglass-hide-body": [
    "a4",
    7,
    3
  ],
  "loom-voidglass-hide-legs": [
    "a4",
    0,
    4
  ],
  "loom-voidglass-hide-boots": [
    "a4",
    1,
    4
  ],
  "loom-voidglass-hide-gloves": [
    "a4",
    2,
    4
  ],
  "loom-voidglass-robe": [
    "a4",
    3,
    4
  ],
  "loom-voidglass-amulet": [
    "a4",
    4,
    4
  ],
  "fletch-arrow-10": [
    "a4",
    5,
    4
  ],
  "fletch-bow-10": [
    "a4",
    6,
    4
  ],
  "vial-10": [
    "a4",
    7,
    4
  ],
  "sigil-10": [
    "a4",
    0,
    5
  ],
  "timber-11": [
    "a4",
    1,
    5
  ],
  "vein-11": [
    "a4",
    2,
    5
  ],
  "smelt-11": [
    "a4",
    3,
    5
  ],
  "trawl-11": [
    "a4",
    4,
    5
  ],
  "cook-11": [
    "a4",
    5,
    5
  ],
  "ember-11": [
    "a4",
    6,
    5
  ],
  "smith-mythic-saber": [
    "a4",
    7,
    5
  ],
  "smith-mythic-cleaver": [
    "a4",
    0,
    6
  ],
  "smith-mythic-needle": [
    "a4",
    1,
    6
  ],
  "smith-mythic-crozier": [
    "a4",
    2,
    6
  ],
  "smith-mythic-helm": [
    "a4",
    3,
    6
  ],
  "smith-mythic-body": [
    "a4",
    4,
    6
  ],
  "smith-mythic-legs": [
    "a4",
    5,
    6
  ],
  "smith-mythic-boots": [
    "a4",
    6,
    6
  ],
  "smith-mythic-gloves": [
    "a4",
    7,
    6
  ],
  "smith-mythic-shield": [
    "a4",
    0,
    7
  ],
  "loom-mythic-hide-cape": [
    "a4",
    1,
    7
  ],
  "loom-mythic-hide-body": [
    "a4",
    2,
    7
  ],
  "loom-mythic-hide-legs": [
    "a4",
    3,
    7
  ],
  "loom-mythic-hide-boots": [
    "a4",
    4,
    7
  ],
  "loom-mythic-hide-gloves": [
    "a4",
    5,
    7
  ],
  "loom-mythic-robe": [
    "a4",
    6,
    7
  ],
  "loom-mythic-amulet": [
    "a4",
    7,
    7
  ],
  "fletch-arrow-11": [
    "a5",
    0,
    0
  ],
  "fletch-bow-11": [
    "a5",
    1,
    0
  ],
  "vial-11": [
    "a5",
    2,
    0
  ],
  "sigil-11": [
    "a5",
    3,
    0
  ],
  "timber-12": [
    "a5",
    4,
    0
  ],
  "vein-12": [
    "a5",
    5,
    0
  ],
  "smelt-12": [
    "a5",
    6,
    0
  ],
  "trawl-12": [
    "a5",
    7,
    0
  ],
  "cook-12": [
    "a5",
    0,
    1
  ],
  "ember-12": [
    "a5",
    1,
    1
  ],
  "smith-astral-saber": [
    "a5",
    2,
    1
  ],
  "smith-astral-cleaver": [
    "a5",
    3,
    1
  ],
  "smith-astral-needle": [
    "a5",
    4,
    1
  ],
  "smith-astral-crozier": [
    "a5",
    5,
    1
  ],
  "smith-astral-helm": [
    "a5",
    6,
    1
  ],
  "smith-astral-body": [
    "a5",
    7,
    1
  ],
  "smith-astral-legs": [
    "a5",
    0,
    2
  ],
  "smith-astral-boots": [
    "a5",
    1,
    2
  ],
  "smith-astral-gloves": [
    "a5",
    2,
    2
  ],
  "smith-astral-shield": [
    "a5",
    3,
    2
  ],
  "loom-astral-hide-cape": [
    "a5",
    4,
    2
  ],
  "loom-astral-hide-body": [
    "a5",
    5,
    2
  ],
  "loom-astral-hide-legs": [
    "a5",
    6,
    2
  ],
  "loom-astral-hide-boots": [
    "a5",
    7,
    2
  ],
  "loom-astral-hide-gloves": [
    "a5",
    0,
    3
  ],
  "loom-astral-robe": [
    "a5",
    1,
    3
  ],
  "loom-astral-amulet": [
    "a5",
    2,
    3
  ],
  "fletch-arrow-12": [
    "a5",
    3,
    3
  ],
  "fletch-bow-12": [
    "a5",
    4,
    3
  ],
  "vial-12": [
    "a5",
    5,
    3
  ],
  "sigil-12": [
    "a5",
    6,
    3
  ],
  "timber-13": [
    "a5",
    7,
    3
  ],
  "vein-13": [
    "a5",
    0,
    4
  ],
  "smelt-13": [
    "a5",
    1,
    4
  ],
  "trawl-13": [
    "a5",
    2,
    4
  ],
  "cook-13": [
    "a5",
    3,
    4
  ],
  "ember-13": [
    "a5",
    4,
    4
  ],
  "smith-veilborn-saber": [
    "a5",
    5,
    4
  ],
  "smith-veilborn-cleaver": [
    "a5",
    6,
    4
  ],
  "smith-veilborn-needle": [
    "a5",
    7,
    4
  ],
  "smith-veilborn-crozier": [
    "a5",
    0,
    5
  ],
  "smith-veilborn-helm": [
    "a5",
    1,
    5
  ],
  "smith-veilborn-body": [
    "a5",
    2,
    5
  ],
  "smith-veilborn-legs": [
    "a5",
    3,
    5
  ],
  "smith-veilborn-boots": [
    "a5",
    4,
    5
  ],
  "smith-veilborn-gloves": [
    "a5",
    5,
    5
  ],
  "smith-veilborn-shield": [
    "a5",
    6,
    5
  ],
  "loom-veilborn-hide-cape": [
    "a5",
    7,
    5
  ],
  "loom-veilborn-hide-body": [
    "a5",
    0,
    6
  ],
  "loom-veilborn-hide-legs": [
    "a5",
    1,
    6
  ],
  "loom-veilborn-hide-boots": [
    "a5",
    2,
    6
  ],
  "loom-veilborn-hide-gloves": [
    "a5",
    3,
    6
  ],
  "loom-veilborn-robe": [
    "a5",
    4,
    6
  ],
  "loom-veilborn-amulet": [
    "a5",
    5,
    6
  ],
  "fletch-arrow-13": [
    "a5",
    6,
    6
  ],
  "fletch-bow-13": [
    "a5",
    7,
    6
  ],
  "vial-13": [
    "a5",
    0,
    7
  ],
  "sigil-13": [
    "a5",
    1,
    7
  ],
  "whisper-dock-beggar": [
    "a5",
    2,
    7
  ],
  "whisper-lantern-clerk": [
    "a5",
    3,
    7
  ],
  "whisper-ashfen-herbalist": [
    "a5",
    4,
    7
  ],
  "whisper-bastion-guard": [
    "a5",
    5,
    7
  ],
  "whisper-choir-monk": [
    "a5",
    6,
    7
  ],
  "whisper-star-merchant": [
    "a5",
    7,
    7
  ],
  "whisper-void-diplomat": [
    "a6",
    0,
    0
  ],
  "whisper-veil-regent": [
    "a6",
    1,
    0
  ],
  "course-lap": [
    "a6",
    2,
    0
  ],
  "chart-study-the-hatchet": [
    "a6",
    3,
    0
  ],
  "chart-study-the-net": [
    "a6",
    4,
    0
  ],
  "chart-study-the-pick": [
    "a6",
    5,
    0
  ],
  "chart-study-the-hearth": [
    "a6",
    6,
    0
  ],
  "chart-study-the-anvil": [
    "a6",
    7,
    0
  ],
  "chart-study-the-blade": [
    "a6",
    0,
    1
  ],
  "chart-study-the-bow": [
    "a6",
    1,
    1
  ],
  "chart-study-the-crozier": [
    "a6",
    2,
    1
  ],
  "chart-study-the-veil": [
    "a6",
    3,
    1
  ],
  "timber": [
    "skills",
    0,
    0
  ],
  "trawl": [
    "skills",
    1,
    0
  ],
  "vein": [
    "skills",
    2,
    0
  ],
  "ember": [
    "skills",
    3,
    0
  ],
  "hearth": [
    "skills",
    4,
    0
  ],
  "anvil": [
    "skills",
    0,
    1
  ],
  "fletch": [
    "skills",
    1,
    1
  ],
  "loom": [
    "skills",
    2,
    1
  ],
  "sigil": [
    "skills",
    3,
    1
  ],
  "vial": [
    "skills",
    4,
    1
  ],
  "course": [
    "skills",
    0,
    2
  ],
  "whisper": [
    "skills",
    1,
    2
  ],
  "soil": [
    "skills",
    2,
    2
  ],
  "drove": [
    "skills",
    3,
    2
  ],
  "chart": [
    "skills",
    4,
    2
  ],
  "might": [
    "skills",
    0,
    3
  ],
  "guard": [
    "skills",
    1,
    3
  ],
  "vitality": [
    "skills",
    2,
    3
  ],
  "mark": [
    "skills",
    3,
    3
  ],
  "weave": [
    "skills",
    4,
    3
  ],
  "vow": [
    "skills",
    0,
    4
  ],
  "bounty": [
    "skills",
    1,
    4
  ],
  "silent-stacks-boss": [
    "misc",
    0,
    0
  ],
  "the-last-page-boss": [
    "misc",
    1,
    0
  ],
  "dock-vault": [
    "misc",
    2,
    0
  ],
  "sewer-reliquary": [
    "misc",
    3,
    0
  ],
  "fen-crown": [
    "misc",
    4,
    0
  ],
  "choir-spire": [
    "misc",
    5,
    0
  ],
  "pyre-cathedral": [
    "misc",
    6,
    0
  ],
  "oathkeep": [
    "misc",
    7,
    0
  ],
  "starwell": [
    "misc",
    0,
    1
  ],
  "veilheart": [
    "misc",
    1,
    1
  ],
  "silent-stacks": [
    "misc",
    2,
    1
  ],
  "the-last-page": [
    "misc",
    3,
    1
  ],
  "pet-timber": [
    "misc",
    4,
    1
  ],
  "pet-trawl": [
    "misc",
    5,
    1
  ],
  "pet-vein": [
    "misc",
    6,
    1
  ],
  "pet-ember": [
    "misc",
    7,
    1
  ],
  "pet-hearth": [
    "misc",
    0,
    2
  ],
  "pet-anvil": [
    "misc",
    1,
    2
  ],
  "pet-fletch": [
    "misc",
    2,
    2
  ],
  "pet-loom": [
    "misc",
    3,
    2
  ],
  "pet-sigil": [
    "misc",
    4,
    2
  ],
  "pet-vial": [
    "misc",
    5,
    2
  ],
  "pet-course": [
    "misc",
    6,
    2
  ],
  "pet-whisper": [
    "misc",
    7,
    2
  ],
  "pet-soil": [
    "misc",
    0,
    3
  ],
  "pet-drove": [
    "misc",
    1,
    3
  ],
  "pet-chart": [
    "misc",
    2,
    3
  ],
  "pet-might": [
    "misc",
    3,
    3
  ],
  "pet-guard": [
    "misc",
    4,
    3
  ],
  "pet-vitality": [
    "misc",
    5,
    3
  ],
  "pet-mark": [
    "misc",
    6,
    3
  ],
  "pet-weave": [
    "misc",
    7,
    3
  ],
  "pet-vow": [
    "misc",
    0,
    4
  ],
  "pet-bounty": [
    "misc",
    1,
    4
  ],
  "tab-workshop": [
    "misc",
    2,
    4
  ],
  "tab-bank": [
    "misc",
    3,
    4
  ],
  "tab-loadout": [
    "misc",
    4,
    4
  ],
  "q-wake": [
    "misc",
    5,
    4
  ],
  "q-fire": [
    "misc",
    6,
    4
  ],
  "q-fish": [
    "misc",
    7,
    4
  ],
  "q-cook": [
    "misc",
    0,
    5
  ],
  "q-blood": [
    "misc",
    1,
    5
  ],
  "q-anvil": [
    "misc",
    2,
    5
  ],
  "q-loom": [
    "misc",
    3,
    5
  ],
  "q-bounty": [
    "misc",
    4,
    5
  ],
  "q-vault": [
    "misc",
    5,
    5
  ],
  "q-whisper": [
    "misc",
    6,
    5
  ],
  "q-soil": [
    "misc",
    7,
    5
  ],
  "q-drove": [
    "misc",
    0,
    6
  ],
  "q-chart": [
    "misc",
    1,
    6
  ],
  "q-course": [
    "misc",
    2,
    6
  ],
  "q-choir": [
    "misc",
    3,
    6
  ],
  "q-vow": [
    "misc",
    4,
    6
  ],
  "q-guild": [
    "misc",
    5,
    6
  ],
  "q-starwell": [
    "misc",
    6,
    6
  ],
  "q-veilheart": [
    "misc",
    7,
    6
  ],
  "q-cap": [
    "misc",
    0,
    7
  ],
  "gust-bolt": [
    "misc",
    1,
    7
  ],
  "ember-lash": [
    "misc",
    2,
    7
  ],
  "tide-ward": [
    "misc",
    3,
    7
  ],
  "stone-spike": [
    "misc",
    4,
    7
  ],
  "blood-pact": [
    "misc",
    5,
    7
  ],
  "void-needle": [
    "misc",
    6,
    7
  ],
  "star-fall": [
    "misc",
    7,
    7
  ],
  "veil-edict": [
    "a6",
    4,
    1
  ],
  "gust-fan": [
    "a6",
    5,
    1
  ],
  "ember-core": [
    "a6",
    6,
    1
  ],
  "tide-lash": [
    "a6",
    7,
    1
  ],
  "stone-wall": [
    "a6",
    0,
    2
  ],
  "mind-spike": [
    "a6",
    1,
    2
  ],
  "blood-rain": [
    "a6",
    2,
    2
  ],
  "void-veil": [
    "a6",
    3,
    2
  ],
  "star-needle": [
    "a6",
    4,
    2
  ],
  "vow-protect": [
    "a6",
    5,
    2
  ],
  "vow-heavy": [
    "a6",
    6,
    2
  ],
  "vow-iron": [
    "a6",
    7,
    2
  ],
  "vow-sight": [
    "a6",
    0,
    3
  ],
  "vow-mind": [
    "a6",
    1,
    3
  ],
  "vow-triangle": [
    "a6",
    2,
    3
  ],
  "vow-leech": [
    "a6",
    3,
    3
  ],
  "vow-smite": [
    "a6",
    4,
    3
  ],
  "vow-still": [
    "a6",
    5,
    3
  ],
  "vow-last": [
    "a6",
    6,
    3
  ],
  "vow-haste": [
    "a6",
    7,
    3
  ],
  "vow-ward": [
    "a6",
    0,
    4
  ],
  "vow-flint": [
    "a6",
    1,
    4
  ],
  "vow-nock": [
    "a6",
    2,
    4
  ],
  "vow-glyph": [
    "a6",
    3,
    4
  ],
  "vow-thick": [
    "a6",
    4,
    4
  ],
  "vow-hunt": [
    "a6",
    5,
    4
  ],
  "vow-quiet": [
    "a6",
    6,
    4
  ],
  "vow-red": [
    "a6",
    7,
    4
  ],
  "vow-blue": [
    "a6",
    0,
    5
  ],
  "vow-green": [
    "a6",
    1,
    5
  ],
  "vow-boss": [
    "a6",
    2,
    5
  ],
  "vow-thin": [
    "a6",
    3,
    5
  ],
  "vow-mirror": [
    "a6",
    4,
    5
  ],
  "vow-star": [
    "a6",
    5,
    5
  ],
  "vow-ash": [
    "a6",
    6,
    5
  ],
  "vow-salt": [
    "a6",
    7,
    5
  ],
  "vow-ink": [
    "a6",
    0,
    6
  ],
  "vow-final": [
    "a6",
    1,
    6
  ],
  "the-hatchet": [
    "a6",
    2,
    6
  ],
  "the-net": [
    "a6",
    3,
    6
  ],
  "the-pick": [
    "a6",
    4,
    6
  ],
  "the-hearth": [
    "a6",
    5,
    6
  ],
  "the-anvil": [
    "a6",
    6,
    6
  ],
  "the-blade": [
    "a6",
    7,
    6
  ],
  "the-bow": [
    "a6",
    0,
    7
  ],
  "the-crozier": [
    "a6",
    1,
    7
  ],
  "the-veil": [
    "a6",
    2,
    7
  ],
  "dust-speed": [
    "a6",
    3,
    7
  ],
  "dust-rare": [
    "a6",
    4,
    7
  ],
  "dust-preserve": [
    "a6",
    5,
    7
  ],
  "dust-xp": [
    "a6",
    6,
    7
  ],
  "dust-str": [
    "a6",
    7,
    7
  ],
  "dust-ward": [
    "i7",
    5,
    0
  ],
  "gloom-ewe": [
    "i7",
    6,
    0
  ],
  "ash-hen": [
    "i7",
    7,
    0
  ],
  "salt-goat": [
    "i7",
    0,
    1
  ],
  "choir-ox": [
    "i7",
    1,
    1
  ],
  "star-moth": [
    "i7",
    2,
    1
  ],
  "void-ram": [
    "i7",
    3,
    1
  ],
  "veil-stag": [
    "i7",
    4,
    1
  ]
};
